dist: bionic
language: erlang
otp_release:
  - 22.0
  - 21.3.8
  - 21.2
  - 21.1
  - 21.0
  - 20.3
  - 20.1
  - 20.0
  - 19.3

services:
  - docker

before_install:
  - docker pull couchdb:2.3.0
  - docker run -d -p 127.0.0.1:5984:5984 -t couchdb:2.3.0
  - "chmod +x bootstrap_travis.sh"
  - "./bootstrap_travis.sh"

install:
  - curl -X PUT -d '0.0.0.0' http://localhost:5984/_node/nonode@nohost/_config/httpd/bind_address
  - "./rebar3 compile"
  
script:  
  - "./rebar3 eunit"