language: erlang
otp_release:
   - 19.3
   - 20.0
   - 20.1

services:
  - couchdb

before_install:
 - "chmod +x bootstrap_travis.sh"
 - "./bootstrap_travis.sh"

install:
  - "./rebar3 compile"

# before_script:
  
script:  
  - "./rebar3 eunit"